######################################################################
# Automatically generated by qmake (2.01a) Tue Aug 2 22:05:17 2016
######################################################################

QT += widgets

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += mainwindow.h
SOURCES += main.cpp mainwindow.cpp
