######################################################################
# Automatically generated by qmake (2.01a) Mon Aug 1 10:29:12 2016
######################################################################

QT += widgets

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += mainwindow.h
SOURCES += main.cpp mainwindow.cpp
